### ISSUE TITLE
scope.$.update() not work for ct-repeat?

### ISSUE THREAD

**Issue by qiaosu** [karlvr/consistent.js#12]
Hey，

I have a table setup like the example table-repeat.html

when i change the dom, and modify the tr‘s order, i want to use scope.$.update() method to update my scope value, but it's not work for this case.

**Comment by karlvr** [comment]
@qiaosu Right, interesting - so are you reordering the `<tr>`s or changing the contents of the `<tr>`s? Could you put an HTML example file into a Gist?
